[package]
name = "rui"
version = "0.1.0"
authors = ["LeymanMA <leymanma@antereal.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "*"